[package]
name = "asmodeus-runner"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[[bin]]
name = "asmodeus-runner"
path = "src/main.rs"

[dependencies]
asmodeus-common = { workspace = true }
asmodeus-dsl = { workspace = true }
asmodeus-safety = { workspace = true }
