[package]
name = "asmodeus-testkit"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
asmodeus-common = { workspace = true }
asmodeus-crypto = { workspace = true }
asmodeus-dsl = { workspace = true }
ed25519-compact = { workspace = true }
